### ISSUE TITLE
Export error is back

### ISSUE THREAD

**Issue by canweriotnow** [yjwen/org-reveal#148]
Same as #135, #146 - `wrong-type-argument` error on export, but with org-mode 20150921

**Comment by yjwen** [comment]
Just tried with org-mode 20150921, but no error found, either with ox-html or ox-reveal.

Could you please send me a sample .org file that can reproduce the issue?

**Comment by jnear** [comment]
I get this error too, using the Readme.org file in the repository:

apply: Wrong type argument: listp, #("Yujie Wen" 0 9 (:parent (#0)))

Using org-mode from elpa:

Org-mode version 8.3.1 (8.3.1-146-gfd8a18-elpa @ /home/jnear/.emacs.d/elpa/org-20150928/)

If I remove the title, author, and email lines from the Readme.org file then the export works fine.

**Comment by jnear** [comment]
Updated to org-mode 8.3.2 (8.3.2-10-g00dacd-elpa @ /home/jnear/.emacs.d/elpa/org-20151005/), the problem went away.

**Comment by canweriotnow** [comment]
Sorry, got distracted, I'll upgrade and try to reproduce and update asap.

**Comment by tworthington** [comment]
I'm on "Org-mode version 8.3.2 (8.3.2-10-g00dacd-elpa @ /home/thomas/.emacs.d/elpa/org-20151005/)" and getting the same error. furthermore,  if I remove the first three lines of Readme.org I get this error instead:

org-reveal-append-frag: Symbol’s function definition is void: mapcar*

I'm on GNU Emacs 25.0.50.2 (x86_64-pc-linux-gnu, GTK+ Version 3.4.2) of 2015-10-14

**Comment by jnear** [comment]
The mapcar* problem is solved by loading the common lisp library:

M-x load-library RET
cl RET

**Comment by tworthington** [comment]
@jnear Thanks, that solved the mapcar* issue.

**Comment by yjwen** [comment]
I installed Org-mode version 20151005 from ELPA, but `(org-version)` give me "Org-mode version 8.3.1 (8.3.1-129-ga7c8d2-elpa @ c:/Users/yujie/AppData/Roaming/.emacs.d/elpa/org-20151005/)".

Strange. Where is 8.3.2?

**Comment by Titan-C** [comment]
I can install the lastest orgmode version org-mode version 8.3.2 (8.3.2-10-g00dacd-elpa @ /home/oscar/.emacs.d/elpa/org-20151005/)
The problem persist

**Comment by yjwen** [comment]
OK. I also installed org-mode 8.3.2. But I didn't encounter the export error.

Based on past experience, the `Wrong type argument` error should be at org-mode side which will also appear when exporting to HTML.

Let me fix the cl library issue first.

**Comment by yjwen** [comment]
Commit 30ff6a4 fixed the `require cl` issue.

**Comment by t-jones** [comment]
This had me pulling out my hair as well, but [uninstalling/re-installing org](http://emacs.stackexchange.com/questions/14763/exporting-org-file-breaks-when-upgrading-to-orgmode-8-3) resolved it for me.  Running latest org from ELPA - Org-mode version 8.3.3 (8.3.3-2-g6bc48c-elpa @ /home/tim/.emacs.d/elpa/org-20160111/).

**Comment by imskull** [comment]
Wow, re-install org works.

**Comment by ryrun** [comment]
Got this error, too. Reinstalling org-mode doesn't work for me.
I'm on windows 7, Org-mode version 8.3.4-39-ge0acd8-elpa, Emacs 25.0.50.1

**Comment by HiroshiMatsumoto** [comment]
I had the same problem.
In my case, on mac environment, changing emacs solved this.
I was using emacs from https://emacsformacosx.com/
Then switching to homebrew emacs solved it.

Both of them are using the same ~/.emacs.d configuration.

**Comment by blallau** [comment]
I have the same problem.
* org-git-version "8.3.4-60-g19cf68-elpa"
* Emacs 24.5.1

**Comment by To1ne** [comment]
I found this _workaround_ solution: http://emacs.stackexchange.com/a/16616/2780
Actually only doing `C-u` `M-x` `org-reload` was enough in my case. But I need to run it every time I restarted emacs (fortunately that is not often).

**Comment by talexand** [comment]
I think this needs to be referred upstream. Org-mode has known problems related to this, one being that you have to make sure `org` is unloaded before you update.

**Comment by achernyak** [comment]
@To1ne Thank you so much, that was the only thing that worked for me. I am on OsX using newest version of everything.

**Comment by karbak** [comment]
Still seeing this happen with:
GNU Emacs 25.1.1 (x86_64-apple-darwin15.6.0, NS appkit-1404.47 Version 10.11.6 (Build 15G1004)) of 2016-10-08
Org-mode version 8.3.6 (8.3.6-6-g194e51-elpa @ /Users/kar/.emacs.d/elpa/org-20161003/)

The StackExchange clean start/uninstall/install method did not work, but the org-reload method did fix the issue. Any luck with taking this upstream?

**Comment by libichong** [comment]
To solve #-TITLE can't be exported problem
1. Manually install elpa package and try several other sources
2. delete all the elc files in org folder, byte-compile the folder 
3.  Replace all the files with older version

**Comment by tosmi** [comment]
same here, running emasc 25.1.1. this comment fixed it for me: https://github.com/yjwen/org-reveal/issues/171#issuecomment-229180318. seems to be a problem with compiling org-mode from elpa if the built in org-mode is already loaded.

**Comment by skyer9** [comment]
@To1ne This has worked for me.

**Comment by jgkamat** [comment]
For anyone still strugging with this, a more permanent solution might me to enable async byte compilation of org for updates. See the [emacs-async readme](https://github.com/jwiegley/emacs-async) for more information. I think it essentially runs a clean background emacs to do the actual byte compile, which ensures you won't get these problems. Magit and helm seem to have this enabled by default.

**Comment by gkbio** [comment]
I got this problem when I upgraded my Org package from the default version.

I fixed the problem without deleting any org folders and just by reloading uncompiled org.

**System Config:**
I am running WSL on windows 10 - > Emacs 25.3.2 and Org 9.1.14

**Solution:**

> Emacs File Menu -> Org -> Refresh/Reload ->**Reload Org Uncompiled C-u C-c C-x !**

**Comment by yjwen** [comment]
Seems the issue has gone. Closing.
